// src/app/layout.jsx
import "./globals.css";

export const metadata = {
  title: "Gouger - Rent Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="font-sans antialiased h-full bg-white text-black">
        <div className="min-h-screen flex flex-col">{children}</div>
      </body>
    </html>
  );
}
